// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuhFxVvN9TSEXoCfEpmHnFh7BolKGPbTA',
    appId: '1:82172650054:web:78f4e602fb8fc9fa2fa047',
    messagingSenderId: '82172650054',
    projectId: 'my-hspl-food',
    authDomain: 'my-hspl-food.firebaseapp.com',
    storageBucket: 'my-hspl-food.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq8L_NqsdoSh462_7ruBZrn3PGZgyN1xU',
    appId: '1:82172650054:android:690e780a36ae7def2fa047',
    messagingSenderId: '82172650054',
    projectId: 'my-hspl-food',
    storageBucket: 'my-hspl-food.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4y9xBhQLEzUL3G5ghnGeDctPJfPZZTgU',
    appId: '1:82172650054:ios:316bedcc4d49a3b42fa047',
    messagingSenderId: '82172650054',
    projectId: 'my-hspl-food',
    storageBucket: 'my-hspl-food.appspot.com',
    iosClientId: '82172650054-dlenl65rqpabk1tk9p8u14vlujlha44i.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.stackFood',
  );
}
